#!/bin/bash
SUPABASE_URL="https://hthjuoswarvsfssxqxxj.supabase.co"
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aGp1b3N3YXJ2c2Zzc3hxeHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1ODkzNTIsImV4cCI6MjA5MjE2NTM1Mn0.DPfKl9RqLWPQNXqsA-QC8kBBa3Qh7pw60NLdwiq-eOc"

echo "=== SPRAWDZAM BRAKUJĄCE TABELE ==="
echo ""
echo "Brakujące tabele:"
echo "- conversation_results (migracja 029)"
echo "- import_events (migracja 027)"
echo ""
echo "Te tabele muszą być utworzone ręcznie przez SQL Editor w Supabase Dashboard."
echo ""
echo "Kroki:"
echo "1. Otwórz: https://supabase.com/dashboard/project/hthjuoswarvsfssxqxxj/sql/new"
echo "2. Skopiuj zawartość: supabase/migrations/029_conversation_results.sql"
echo "3. Uruchom w SQL Editor"
echo "4. Skopiuj zawartość: supabase/migrations/027_import_reliability.sql"
echo "5. Uruchom w SQL Editor"
echo ""
echo "Tabele daily_insights, import_transcripts, user_quotas prawdopodobnie nie mają dedykowanych migracji."
